security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_RANDONNEUR:  ROLE_USER
        ROLE_AGENCE: ROLE_USER
        ROLE_GUIDE: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
               # login_path: fos_user_security_login
                        # if you are using Symfony < 2.8, use the following config instead:
                #csrf_provider: form.csrf_provider
                success_handler: redirect.after.login
               # check_path: /login_check
       # secured_area:
            #anonymous: ~

            oauth:
                #login_path:        /connect
                resource_owners:
                    facebook: "/login/check-facebook"

                login_path:       /login
                #
                failure_path:      /login
                use_forward:       false
                default_target_path: /index
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge

            logout:
               path:    /logout
               target: /login

            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/, role: ROLE_USER }
        - { path: ^/guide/, role: ROLE_GUIDE }
        - { path: ^/agence/, role: ROLE_AGENCE }